import { parseVttToPlainText } from "@nexiforma/shared";

describe("parseVttToPlainText", () => {
  it("extrai falas com identificação de orador", () => {
    const vtt = `WEBVTT

00:00:01.000 --> 00:00:04.000
<v João Silva>Olá, bom dia.</v>

00:00:05.000 --> 00:00:08.000
<v Maria Santos>Tudo bem, obrigada.</v>
`;
    expect(parseVttToPlainText(vtt)).toBe(
      "João Silva: Olá, bom dia.\nMaria Santos: Tudo bem, obrigada.",
    );
  });

  it("ignora linhas de tempo e cabeçalho", () => {
    const vtt = `WEBVTT

NOTE Generated by Teams

1
00:00:00.000 --> 00:00:02.000
Texto simples
`;
    expect(parseVttToPlainText(vtt)).toBe("Texto simples");
  });
});
