import type { GuideDestination } from "./types";

/** Catálogo estático de destinos - evoluível para embeddings locais sem APIs externas. */
export const GUIDE_DESTINATIONS: GuideDestination[] = [
  {
    href: "/",
    label: "Página inicial",
    description: "Website NexiForma e apresentação da plataforma.",
    keywords: ["inicio", "home", "welcome", "website", "landing", "pagina inicial"],
    publicOnly: true,
  },
  {
    href: "/login",
    label: "Entrar",
    description: "Autenticação no portal da entidade formadora.",
    keywords: ["login", "entrar", "acesso", "portal", "autenticacao"],
    publicOnly: true,
  },
  {
    href: "/#funcionalidades",
    label: "Funcionalidades",
    description: "Secção de funcionalidades no website.",
    keywords: ["funcionalidades", "features", "modulos"],
    publicOnly: true,
  },
  {
    href: "/#como-funciona",
    label: "Como funciona",
    description: "Fluxo operacional apresentado no website.",
    keywords: ["como funciona", "fluxo", "processo"],
    publicOnly: true,
  },
  {
    href: "/#integracoes",
    label: "Integrações",
    description: "Integrações nativas apresentadas no website.",
    keywords: ["integracoes", "sigo", "at", "cmd", "stripe"],
    publicOnly: true,
  },
  {
    href: "/plataforma",
    label: "Control Plane",
    description: "Administração global multi-tenant.",
    keywords: ["plataforma", "control plane", "super admin", "tenants"],
    minRole: "super_admin",
  },
  {
    href: "/portal",
    label: "Dashboard",
    description: "Visão geral da entidade formadora.",
    keywords: ["dashboard", "inicio", "home", "painel", "visao geral", "resumo"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/fluxo",
    label: "Fluxo guiado",
    description: "Passo a passo da operação formativa.",
    keywords: ["fluxo", "guiado", "passo a passo", "onboarding operacional"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/calendario",
    label: "Calendário",
    description: "Sessões e eventos formativos.",
    keywords: ["calendario", "agenda", "sessoes", "eventos", "datas"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/relatorios",
    label: "Relatórios",
    description: "Indicadores e exportações.",
    keywords: ["relatorios", "indicadores", "metricas", "estatisticas", "kpi"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/crm",
    label: "CRM Dashboard",
    description: "Pipeline comercial e KPIs.",
    keywords: ["crm", "crm dashboard", "comercial", "vendas", "pipeline", "negocio"],
    minRole: "comercial",
  },
  {
    href: "/portal/crm/leads",
    label: "Leads",
    description: "Prospeção e conversão comercial.",
    keywords: ["leads", "prospeccao", "oportunidades", "contactos comerciais"],
    minRole: "comercial",
  },
  {
    href: "/portal/clientes",
    label: "Clientes",
    description: "Clientes B2B e empresas.",
    keywords: ["entidades", "clientes", "empresas", "b2b", "cliente"],
    minRole: "comercial",
  },
  {
    href: "/portal/parceiros",
    label: "Parceiros",
    description: "Rede de parceiros comerciais.",
    keywords: ["parceiros", "parcerias", "intermediarios"],
    minRole: "comercial",
  },
  {
    href: "/portal/propostas",
    label: "Propostas",
    description: "Propostas comerciais e orçamentos.",
    keywords: ["propostas", "orcamentos", "cotacao", "proposta comercial"],
    minRole: "comercial",
  },
  {
    href: "/portal/crm/faturas",
    label: "Faturas",
    description: "Emissão e gestão de faturas.",
    keywords: ["faturas", "fatura", "faturacao", "documentos fiscais", "at"],
    minRole: "comercial",
  },
  {
    href: "/portal/crm/faturacao",
    label: "Dados de faturação",
    description: "Configuração fiscal e séries AT.",
    keywords: ["dados faturacao", "faturacao", "faturas", "series", "nif empresa", "configuracao fiscal", "saft"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/contratos",
    label: "Contratos",
    description: "Contratos com clientes.",
    keywords: ["contratos", "contrato", "acordo"],
    minRole: "comercial",
  },
  {
    href: "/portal/notificacoes",
    label: "Notificações",
    description: "Alertas e comunicações.",
    keywords: ["notificacoes", "alertas", "avisos", "comunicacoes"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/cursos",
    label: "Cursos",
    description: "Catálogo de cursos formativos.",
    keywords: ["cursos", "curso", "formacao", "programa"],
  },
  {
    href: "/portal/acoes",
    label: "Ações formativas",
    description: "Turmas, sessões e sumários.",
    keywords: ["acoes", "acao formativa", "turmas", "turma", "sumarios", "sumario", "aulas"],
  },
  {
    href: "/portal/catalogo-ufcd",
    label: "Catálogo UFCD",
    description: "Referencial UFCD e áreas.",
    keywords: ["ufcd", "catalogo ufcd", "referencial", "areas formativas"],
  },
  {
    href: "/portal/matriculas",
    label: "Inscrições",
    description: "Matrículas e inscrições.",
    keywords: ["matriculas", "inscricoes", "inscricao", "alunos inscritos"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/formandos",
    label: "Formandos",
    description: "Lista de formandos da entidade.",
    keywords: ["formandos", "alunos", "participantes"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/formadores",
    label: "Formadores",
    description: "Equipa de formadores.",
    keywords: ["formadores", "formador", "trainers", "docentes"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/avaliacoes",
    label: "Avaliações",
    description: "Quizzes e avaliações.",
    keywords: ["avaliacoes", "avaliacao", "quiz", "testes", "provas"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/lms",
    label: "LMS e assiduidade",
    description: "Presenças, Zoom/Teams e painel LMS.",
    keywords: ["lms", "assiduidade", "presencas", "presenca", "zoom", "teams", "online"],
  },
  {
    href: "/portal/conteudos",
    label: "Conteúdos LMS",
    description: "Módulos SCORM e materiais.",
    keywords: ["conteudos", "scorm", "modulos", "materiais", "elearning"],
  },
  {
    href: "/portal/documentos",
    label: "Documentos",
    description: "Arquivo documental.",
    keywords: ["documentos", "ficheiros", "arquivo", "upload"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/compliance",
    label: "Compliance DGERT",
    description: "Checklist e conformidade.",
    keywords: ["compliance", "dgert", "inspecao", "conformidade", "checklist"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/dossie",
    label: "Dossiê e exports",
    description: "Dossiê pedagógico e exportações.",
    keywords: ["dossie", "dossier", "exports", "exportar", "pedagogico", "inspeccao"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/certificados",
    label: "Certificados",
    description: "Emissão de certificados.",
    keywords: ["certificados", "certificado", "cmd", "assinatura"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/sigo",
    label: "SIGO",
    description: "Exportação para SIGO/DGEEC.",
    keywords: ["sigo", "dgeec", "export sigo", "gov"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/rgpd",
    label: "RGPD",
    description: "Privacidade e dados pessoais.",
    keywords: ["rgpd", "gdpr", "privacidade", "dados pessoais", "consentimento"],
  },
  {
    href: "/portal/configuracoes",
    label: "Configurações",
    description: "Definições da entidade.",
    keywords: ["configuracoes", "definicoes", "settings", "preferencias"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/utilizadores",
    label: "Utilizadores",
    description: "Gestão de utilizadores e convites.",
    keywords: ["utilizadores", "users", "convites", "permissoes", "roles"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/integracoes",
    label: "Integrações",
    description: "AT, SIGO, mail, SMS e outras ligações.",
    keywords: ["integracoes", "integracao", "api", "stripe", "webhook"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/enterprise",
    label: "Enterprise",
    description: "SSO OIDC e chaves API.",
    keywords: ["enterprise", "sso", "oidc", "api keys", "chaves api"],
    minRole: "tenant_manager",
  },
  {
    href: "/portal/billing",
    label: "Subscrição",
    description: "Plano SaaS e billing.",
    keywords: ["billing", "subscricao", "plano", "stripe", "pagamento"],
    minRole: "tenant_manager",
  },
  // Portal formando
  {
    href: "/portal/formando",
    label: "Início formando",
    description: "Área principal do formando.",
    keywords: ["inicio", "home", "dashboard", "formando"],
    formandoOnly: true,
  },
  {
    href: "/portal/formando/calendario",
    label: "Calendário formando",
    description: "Sessões e horários.",
    keywords: ["calendario", "agenda", "sessoes", "horario"],
    formandoOnly: true,
  },
  {
    href: "/portal/formando/catalogo",
    label: "Catálogo formando",
    description: "Cursos disponíveis.",
    keywords: ["catalogo", "cursos", "formacao disponivel"],
    formandoOnly: true,
  },
  {
    href: "/portal/formando/inscricoes",
    label: "Minhas inscrições",
    description: "Estado das matrículas.",
    keywords: ["inscricoes", "matriculas", "minhas formacoes"],
    formandoOnly: true,
  },
  {
    href: "/portal/formando/rgpd",
    label: "Privacidade RGPD",
    description: "Consulta e alteração do consentimento sobre dados pessoais.",
    keywords: ["rgpd", "gdpr", "privacidade", "consentimento", "dados pessoais"],
    formandoOnly: true,
  },
  {
    href: "/portal/formando/perfil",
    label: "Perfil formando",
    description: "Dados pessoais e RGPD.",
    keywords: ["perfil", "conta", "dados", "rgpd", "exportar dados"],
    formandoOnly: true,
  },
];
